### PR TITLE
Prepare for symfony 5 and PHP8

### PR DESCRIPTION
**Pull request by toooni**

### CODE REVIEW

**Comment by jean-gui** [comment]
Thanks @toooni for this. I believe those changes are backwards compatible with sf4. Can you confirm that?

**Comment by toooni** [comment]
Yes. I've updated the dev dependencies and fixed the travis config to reflect that. I am sorry that I've made a mess with the commits. I'd recommend to squash the commits while merging.

**Comment by jean-gui** [comment]
Thanks, merged!

**Comment by toooni** [comment]
Thanks to you. Can you also tag a new release?

**Comment by jean-gui** [comment]
Done.

**Pull request merged**
